project:
  type: website
  output-dir: ../docs/slides
  render:
    # - "background/background.qmd"
    # - "background/rsa.qmd"
    # - "pds-intro/pds-intro.qmd"
    - "adjectives/adjectives-intro.qmd"
    # - "factivity/factivity.qmd"
    # - "qud/qud.qmd"
 
format:
  revealjs:
    theme: default
    highlight-style: gruvbox-dark
    slide-number: true
    chalkboard: true
    incremental: true
    preview-links: auto
    css: styles.css
    footer: "Probabilistic dynamic semantics"
